name: bjorn_utils
channels:
  - conda-forge
dependencies:
  - biopython
  - black
  - isort
  - mypy
  - pandas
  - pip==21.1.3
  - pip:
    - gspread

# add this back once we get bjorn as a module
# git+https://github.com/andersen-lab/bjorn.git